# Multi-stage build untuk API
FROM golang:1.22-alpine AS build
WORKDIR /app
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/api ./cmd/api

FROM gcr.io/distroless/static-debian12
ENV HTTP_PORT=3000
EXPOSE 3000
COPY --from=build /bin/api /api
USER 65532:65532
ENTRYPOINT ["/api"]
