// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/player.proto

package playerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Id                    string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName             string                  `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName              string                  `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username              string                  `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                 string                  `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneCountryCode      string                  `protobuf:"bytes,6,opt,name=phone_country_code,json=phoneCountryCode,proto3" json:"phone_country_code,omitempty"`
	PhoneNumber           string                  `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Nationality           string                  `protobuf:"bytes,8,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Gender                string                  `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	ImageFileId           *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=image_file_id,json=imageFileId,proto3" json:"image_file_id,omitempty"`
	OneSignalId           *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=one_signal_id,json=oneSignalId,proto3" json:"one_signal_id,omitempty"`
	ReferralCode          string                  `protobuf:"bytes,12,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	Experienced           string                  `protobuf:"bytes,13,opt,name=experienced,proto3" json:"experienced,omitempty"`
	SubscriptionId        string                  `protobuf:"bytes,14,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PartnerSubscriptions  string                  `protobuf:"bytes,15,opt,name=partner_subscriptions,json=partnerSubscriptions,proto3" json:"partner_subscriptions,omitempty"`
	IsBetaTester          *wrapperspb.BoolValue   `protobuf:"bytes,16,opt,name=is_beta_tester,json=isBetaTester,proto3" json:"is_beta_tester,omitempty"`
	IsOnboarding          *wrapperspb.BoolValue   `protobuf:"bytes,17,opt,name=is_onboarding,json=isOnboarding,proto3" json:"is_onboarding,omitempty"`
	IsFirstBuy            *wrapperspb.BoolValue   `protobuf:"bytes,18,opt,name=is_first_buy,json=isFirstBuy,proto3" json:"is_first_buy,omitempty"`
	IsDefaultUsername     *wrapperspb.BoolValue   `protobuf:"bytes,19,opt,name=is_default_username,json=isDefaultUsername,proto3" json:"is_default_username,omitempty"`
	IsFirstBuyGolfCourse  *wrapperspb.BoolValue   `protobuf:"bytes,20,opt,name=is_first_buy_golf_course,json=isFirstBuyGolfCourse,proto3" json:"is_first_buy_golf_course,omitempty"`
	Dob                   *timestamppb.Timestamp  `protobuf:"bytes,21,opt,name=dob,proto3" json:"dob,omitempty"`
	CreatedAt             *timestamppb.Timestamp  `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp  `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt             *timestamppb.Timestamp  `protobuf:"bytes,24,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Password              string                  `protobuf:"bytes,25,opt,name=password,proto3" json:"password,omitempty"`
	EmailVerificationCode string                  `protobuf:"bytes,26,opt,name=email_verification_code,json=emailVerificationCode,proto3" json:"email_verification_code,omitempty"`
	EmailTemporary        string                  `protobuf:"bytes,27,opt,name=email_temporary,json=emailTemporary,proto3" json:"email_temporary,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Player) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Player) GetPhoneCountryCode() string {
	if x != nil {
		return x.PhoneCountryCode
	}
	return ""
}

func (x *Player) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Player) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Player) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Player) GetImageFileId() *wrapperspb.StringValue {
	if x != nil {
		return x.ImageFileId
	}
	return nil
}

func (x *Player) GetOneSignalId() *wrapperspb.StringValue {
	if x != nil {
		return x.OneSignalId
	}
	return nil
}

func (x *Player) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *Player) GetExperienced() string {
	if x != nil {
		return x.Experienced
	}
	return ""
}

func (x *Player) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Player) GetPartnerSubscriptions() string {
	if x != nil {
		return x.PartnerSubscriptions
	}
	return ""
}

func (x *Player) GetIsBetaTester() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsBetaTester
	}
	return nil
}

func (x *Player) GetIsOnboarding() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsOnboarding
	}
	return nil
}

func (x *Player) GetIsFirstBuy() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsFirstBuy
	}
	return nil
}

func (x *Player) GetIsDefaultUsername() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDefaultUsername
	}
	return nil
}

func (x *Player) GetIsFirstBuyGolfCourse() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsFirstBuyGolfCourse
	}
	return nil
}

func (x *Player) GetDob() *timestamppb.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *Player) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Player) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Player) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Player) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Player) GetEmailVerificationCode() string {
	if x != nil {
		return x.EmailVerificationCode
	}
	return ""
}

func (x *Player) GetEmailTemporary() string {
	if x != nil {
		return x.EmailTemporary
	}
	return ""
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,28,opt,name=key,proto3" json:"key,omitempty"`
	FindBy        string                 `protobuf:"bytes,29,opt,name=find_by,json=findBy,proto3" json:"find_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_proto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetPlayerRequest) GetFindBy() string {
	if x != nil {
		return x.FindBy
	}
	return ""
}

type GetPlayerByPhoneRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber      string                 `protobuf:"bytes,30,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneCountryCode string                 `protobuf:"bytes,31,opt,name=phone_country_code,json=phoneCountryCode,proto3" json:"phone_country_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPlayerByPhoneRequest) Reset() {
	*x = GetPlayerByPhoneRequest{}
	mi := &file_proto_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByPhoneRequest) ProtoMessage() {}

func (x *GetPlayerByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerByPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetPlayerByPhoneRequest) GetPhoneCountryCode() string {
	if x != nil {
		return x.PhoneCountryCode
	}
	return ""
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_proto_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_proto_player_proto protoreflect.FileDescriptor

const file_proto_player_proto_rawDesc = "" +
	"\n" +
	"\x12proto/player.proto\x12\x06player\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf7\t\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12,\n" +
	"\x12phone_country_code\x18\x06 \x01(\tR\x10phoneCountryCode\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12 \n" +
	"\vnationality\x18\b \x01(\tR\vnationality\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12@\n" +
	"\rimage_file_id\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\vimageFileId\x12@\n" +
	"\rone_signal_id\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\voneSignalId\x12#\n" +
	"\rreferral_code\x18\f \x01(\tR\freferralCode\x12 \n" +
	"\vexperienced\x18\r \x01(\tR\vexperienced\x12'\n" +
	"\x0fsubscription_id\x18\x0e \x01(\tR\x0esubscriptionId\x123\n" +
	"\x15partner_subscriptions\x18\x0f \x01(\tR\x14partnerSubscriptions\x12@\n" +
	"\x0eis_beta_tester\x18\x10 \x01(\v2\x1a.google.protobuf.BoolValueR\fisBetaTester\x12?\n" +
	"\ris_onboarding\x18\x11 \x01(\v2\x1a.google.protobuf.BoolValueR\fisOnboarding\x12<\n" +
	"\fis_first_buy\x18\x12 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isFirstBuy\x12J\n" +
	"\x13is_default_username\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueR\x11isDefaultUsername\x12R\n" +
	"\x18is_first_buy_golf_course\x18\x14 \x01(\v2\x1a.google.protobuf.BoolValueR\x14isFirstBuyGolfCourse\x12,\n" +
	"\x03dob\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x03dob\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1a\n" +
	"\bpassword\x18\x19 \x01(\tR\bpassword\x126\n" +
	"\x17email_verification_code\x18\x1a \x01(\tR\x15emailVerificationCode\x12'\n" +
	"\x0femail_temporary\x18\x1b \x01(\tR\x0eemailTemporary\"=\n" +
	"\x10GetPlayerRequest\x12\x10\n" +
	"\x03key\x18\x1c \x01(\tR\x03key\x12\x17\n" +
	"\afind_by\x18\x1d \x01(\tR\x06findBy\"j\n" +
	"\x17GetPlayerByPhoneRequest\x12!\n" +
	"\fphone_number\x18\x1e \x01(\tR\vphoneNumber\x12,\n" +
	"\x12phone_country_code\x18\x1f \x01(\tR\x10phoneCountryCode\"=\n" +
	"\x11GetPlayerResponse\x12(\n" +
	"\aplayers\x18\x01 \x03(\v2\x0e.player.PlayerR\aplayers2\xa1\x01\n" +
	"\rPlayerService\x12@\n" +
	"\tGetPlayer\x12\x18.player.GetPlayerRequest\x1a\x19.player.GetPlayerResponse\x12N\n" +
	"\x10GetPlayerByPhone\x12\x1f.player.GetPlayerByPhoneRequest\x1a\x19.player.GetPlayerResponseB,Z*getswing.app/player-service/proto;playerpbb\x06proto3"

var (
	file_proto_player_proto_rawDescOnce sync.Once
	file_proto_player_proto_rawDescData []byte
)

func file_proto_player_proto_rawDescGZIP() []byte {
	file_proto_player_proto_rawDescOnce.Do(func() {
		file_proto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)))
	})
	return file_proto_player_proto_rawDescData
}

var file_proto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_player_proto_goTypes = []any{
	(*Player)(nil),                  // 0: player.Player
	(*GetPlayerRequest)(nil),        // 1: player.GetPlayerRequest
	(*GetPlayerByPhoneRequest)(nil), // 2: player.GetPlayerByPhoneRequest
	(*GetPlayerResponse)(nil),       // 3: player.GetPlayerResponse
	(*wrapperspb.StringValue)(nil),  // 4: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),    // 5: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_proto_player_proto_depIdxs = []int32{
	4,  // 0: player.Player.image_file_id:type_name -> google.protobuf.StringValue
	4,  // 1: player.Player.one_signal_id:type_name -> google.protobuf.StringValue
	5,  // 2: player.Player.is_beta_tester:type_name -> google.protobuf.BoolValue
	5,  // 3: player.Player.is_onboarding:type_name -> google.protobuf.BoolValue
	5,  // 4: player.Player.is_first_buy:type_name -> google.protobuf.BoolValue
	5,  // 5: player.Player.is_default_username:type_name -> google.protobuf.BoolValue
	5,  // 6: player.Player.is_first_buy_golf_course:type_name -> google.protobuf.BoolValue
	6,  // 7: player.Player.dob:type_name -> google.protobuf.Timestamp
	6,  // 8: player.Player.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: player.Player.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 10: player.Player.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 11: player.GetPlayerResponse.players:type_name -> player.Player
	1,  // 12: player.PlayerService.GetPlayer:input_type -> player.GetPlayerRequest
	2,  // 13: player.PlayerService.GetPlayerByPhone:input_type -> player.GetPlayerByPhoneRequest
	3,  // 14: player.PlayerService.GetPlayer:output_type -> player.GetPlayerResponse
	3,  // 15: player.PlayerService.GetPlayerByPhone:output_type -> player.GetPlayerResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_player_proto_init() }
func file_proto_player_proto_init() {
	if File_proto_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_player_proto_goTypes,
		DependencyIndexes: file_proto_player_proto_depIdxs,
		MessageInfos:      file_proto_player_proto_msgTypes,
	}.Build()
	File_proto_player_proto = out.File
	file_proto_player_proto_goTypes = nil
	file_proto_player_proto_depIdxs = nil
}
